### ISSUE TITLE
这个仓库里的代码是不是没有对属性的操作啊？

### ISSUE THREAD

**Issue by laohuijiadezhu** [LucasBoTang/ModularGAN#1]
我发现Solve类里的self.selected_attrs并没有被哪个函数调用，不知道是我看漏了，还是确实没有写？没有写的话应该怎么写呢？

**Comment by LucasBoTang** [comment]
selected_attrs并没有在solver中被调用，而是在loader中，抱歉这是一个冗余的属性。谢谢提醒。

selected_attrs is not called in the "solver", but in the "loader". Sorry, this is a redundant attribute in "solver". Thank you.
